FROM apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

USER root

WORKDIR ${SPARK_HOME}
ENV PATH="/opt/spark/sbin:/opt/spark/bin:${PATH}"

ENV SPARK_VERSION_SHORT=3.5
ENV SPARK_VERSION=3.5.1
ENV AWS_SDK_VERSION=1.12.773
ENV HADOOP_AWS_VERSION=3.3.4
ENV SPARK_HADOOP_CLOUD=2.12

# Configure SPARK
RUN apt-get update -y && apt-get install -y curl wget
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar -o ${SPARK_HOME}/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar -o ${SPARK_HOME}/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-hadoop-cloud_${SPARK_HADOOP_CLOUD}/${SPARK_VERSION}/spark-hadoop-cloud_${SPARK_HADOOP_CLOUD}-${SPARK_VERSION}.jar -o ${SPARK_HOME}/jars/spark-hadoop-cloud_${SPARK_HADOOP_CLOUD}-${SPARK_VERSION}.jar


# Configure ICEBERG
ENV ICEBERG_VERSION=1.6.0
ENV AWS_SDK_BUNDLE_VERSION=2.20.18

RUN curl https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-${SPARK_VERSION_SHORT}_2.12/${ICEBERG_VERSION}/iceberg-spark-runtime-${SPARK_VERSION_SHORT}_2.12-${ICEBERG_VERSION}.jar -o ${SPARK_HOME}/jars/iceberg-spark-runtime-${SPARK_VERSION_SHORT}_2.12-${ICEBERG_VERSION}.jar
RUN curl https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/${AWS_SDK_BUNDLE_VERSION}/bundle-${AWS_SDK_BUNDLE_VERSION}.jar -Lo /opt/spark/jars/aws-bundle-${AWS_SDK_BUNDLE_VERSION}.jar
RUN curl https://repo1.maven.org/maven2/software/amazon/awssdk/url-connection-client/${AWS_SDK_BUNDLE_VERSION}/url-connection-client-${AWS_SDK_BUNDLE_VERSION}.jar -Lo /opt/spark/jars/url-connection-client-${AWS_SDK_BUNDLE_VERSION}.jar


# Configure ZSH
RUN apt-get install -y zsh git
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
ENV TERM xterm
ENV ZSH_THEME robbyrussell
RUN chsh -s /usr/bin/zsh

# Configure PYTHON
ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.7-src.zip:$PYTHONPATH
ENV SPARK_HOME=/opt/spark
COPY ./src/jupyter/requirements.txt /opt/requirements.txt
RUN pip3 install -r /opt/requirements.txt
COPY ./src/jupyter/jupyter_server_config.py /root/.jupyter/
COPY ./src/jupyter/themes.jupyterlab-settings /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/
COPY ./src/jupyter/start-jupyter.sh /opt/spark/start-jupyter.sh
COPY ./src/jupyter/init_spark.py /opt/spark/python/init_spark.py
COPY ./src/spark/spark-env.sh /opt/spark/conf/spark-env.sh
RUN chmod +x /opt/spark/start-jupyter.sh && \
    sed -i 's/\r$//' /opt/spark/conf/spark-env.sh

# Create the assembly directory structure that PySpark expects
# PySpark looks for JARs in /opt/spark/assembly/target/scala-2.12/jars
# but in Spark 3.5.1 they are in /opt/spark/jars
RUN mkdir -p /opt/spark/assembly/target/scala-2.12 && \
    ln -sf /opt/spark/jars /opt/spark/assembly/target/scala-2.12/jars


RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["tail", "-f", "/dev/null"]
